name: Validate PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for unwanted files
        run: |
          git diff --name-only origin/main | grep -E '(^\.dart_tool/|pubspec.lock)' && \
          echo "❌ Unwanted file changes detected. Please remove pubspec.lock or .dart_tool changes." && exit 1 || \
          echo "✅ No unwanted file changes."
